Twitch:
  # Twitch username
  User: mancert
  # Twitch key
  Token: oauth:23odvh9zs6kiz2flm03i5o0efp1otz
  # Relay chat between channels? on or off
  Relay: off
  Channels:
    - mancert
    - thelvaen_mandel